-- MySQL Script generated by MySQL Workbench
-- Fri Mar 24 21:35:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbms` DEFAULT CHARACTER SET utf8mb3 ;
USE `dbms` ;

-- -----------------------------------------------------
-- Table `dbms`.`classification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`classification` (
  `classification_id` INT NOT NULL AUTO_INCREMENT,
  `classification_code` VARCHAR(10) NOT NULL,
  `classification_title` VARCHAR(100) NOT NULL,
  `classification_parent` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`classification_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbms`.`access_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`access_classe` (
  `access_classe_id` INT NOT NULL AUTO_INCREMENT,
  `access_classe_code` VARCHAR(10) NOT NULL,
  `access_classe_description` TEXT NOT NULL,
  `classification_id` INT NOT NULL,
  PRIMARY KEY (`access_classe_id`, `classification_id`),
  INDEX `fk_classification_to_access_classe_idx` (`classification_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbms`.`dolly`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`dolly` (
  `dolly_id` INT NOT NULL AUTO_INCREMENT,
  `dolly_title` VARCHAR(100) NOT NULL,
  `dolly_observation` TEXT NULL,
  PRIMARY KEY (`dolly_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbms`.`communicability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`communicability` (
  `communicability_id` INT NOT NULL AUTO_INCREMENT,
  `communicability_time` INT NOT NULL,
  `communicability_title` VARCHAR(100) NOT NULL,
  `communicability_reference` TEXT NOT NULL,
  `classification_id` INT NOT NULL,
  PRIMARY KEY (`communicability_id`),
  INDEX `fk_classification_to_communicability_idx` (`classification_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbms`.`deposit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`deposit` (
  `deposit_id` INT NOT NULL AUTO_INCREMENT,
  `deposit_reference` VARCHAR(10) NOT NULL,
  `deposit_title` VARCHAR(100) NOT NULL,
  `deposit_observation` TEXT NULL,
  PRIMARY KEY (`deposit_id`),
  UNIQUE INDEX `deposit_reference_UNIQUE` (`deposit_reference` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbms`.`keywords_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`keywords_type` (
  `keywords_type_id` INT NOT NULL,
  `keywords_type_title` VARCHAR(30) NULL,
  `keywords_type_observation` TEXT(100) NULL,
  PRIMARY KEY (`keywords_type_id`),
  UNIQUE INDEX `keywords_type_title_UNIQUE` (`keywords_type_title` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbms`.`keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`keywords` (
  `keyword_id` INT NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(250) CHARACTER SET 'utf8mb3' NOT NULL,
  `keywords_type_id` INT NOT NULL,
  PRIMARY KEY (`keyword_id`),
  INDEX `fk_keywords_type_to_keywords_idx` (`keywords_type_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbms`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_pseudo` VARCHAR(10) NOT NULL,
  `user_name` VARCHAR(250) NOT NULL,
  `user_surname` VARCHAR(250) NULL,
  `user_password` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbms`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`organization` (
  `organization_id` INT NOT NULL AUTO_INCREMENT,
  `organization_code` INT NOT NULL,
  `organization_title` VARCHAR(100) NOT NULL,
  `organization_observation` TEXT NULL,
  `organization_parent` VARCHAR(100) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`organization_id`),
  INDEX `fk_user_to_organization_idx` (`user_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbms`.`records_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`records_status` (
  `records_status_id` INT NOT NULL,
  `records_status_title` VARCHAR(100) NOT NULL,
  `records_status_observation` TEXT(250) NULL,
  PRIMARY KEY (`records_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbms`.`records_support`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`records_support` (
  `records_support_id` INT NOT NULL,
  `records_support_title` VARCHAR(100) NOT NULL,
  `records_support_observation` TEXT(250) NULL,
  PRIMARY KEY (`records_support_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbms`.`records_link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`records_link` (
  `records_link_id` INT NOT NULL AUTO_INCREMENT,
  `records_id` INT NOT NULL,
  `records_link_parent_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`records_link_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbms`.`shelves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`shelves` (
  `shelves_id` INT NOT NULL AUTO_INCREMENT,
  `shelves_title` VARCHAR(30) NOT NULL,
  `shelves_ear` VARCHAR(10) NOT NULL,
  `shelves_colonne` VARCHAR(10) NOT NULL,
  `shelves_table` VARCHAR(10) NOT NULL,
  `deposit_id` INT NOT NULL,
  PRIMARY KEY (`shelves_id`),
  INDEX `fk_deposit_to_shelves_idx` (`deposit_id` ASC) VISIBLE,
  UNIQUE INDEX `shelves_title_UNIQUE` (`shelves_title` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbms`.`container_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`container_state` (
  `container_state_id` INT NOT NULL AUTO_INCREMENT,
  `container_state_type` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`container_state_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbms`.`container_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`container_type` (
  `container_type_id` INT NOT NULL,
  `container_type_title` VARCHAR(30) NOT NULL,
  `container_type_observation` TEXT(100) NULL,
  PRIMARY KEY (`container_type_id`),
  UNIQUE INDEX `container_type_title_UNIQUE` (`container_type_title` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbms`.`container`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`container` (
  `container_id` INT NOT NULL AUTO_INCREMENT,
  `container_reference` VARCHAR(20) NOT NULL,
  `container_size` VARCHAR(20) NOT NULL,
  `shelves_id` INT NULL,
  `container_state_id` INT NOT NULL,
  `container_type_id` INT NOT NULL,
  PRIMARY KEY (`container_id`),
  INDEX `fk_shelves_to_container_idx` (`shelves_id` ASC) VISIBLE,
  INDEX `fk_container_state_to_container_idx` (`container_state_id` ASC) VISIBLE,
  INDEX `fk_container_state_to_container_idx` (`container_type_id` ASC) VISIBLE,
  UNIQUE INDEX `container_reference_UNIQUE` (`container_reference` ASC) VISIBLE,
  CONSTRAINT `fk_shelves_to_container_dk`
    FOREIGN KEY (`shelves_id`)
    REFERENCES `dbms`.`shelves` (`shelves_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_container_state_to_container_dk`
    FOREIGN KEY (`container_state_id`)
    REFERENCES `dbms`.`container_state` (`container_state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_container_type_to_container_dk`
    FOREIGN KEY (`container_type_id`)
    REFERENCES `dbms`.`container_type` (`container_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbms`.`records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`records` (
  `id_records` INT NOT NULL AUTO_INCREMENT,
  `records_title` TEXT NOT NULL,
  `records_date_start` DATE NOT NULL,
  `records_date_end` DATE NULL,
  `records_observation` TEXT NULL,
  `records_status_id` INT NOT NULL,
  `records_support_id` INT NOT NULL,
  `records_link_id` INT NULL,
  `container_id` INT NOT NULL,
  `classification_id` INT NOT NULL,
  PRIMARY KEY (`id_records`),
  INDEX `fk_records_status_to_records_idx` (`records_status_id` ASC) VISIBLE,
  INDEX `fk_records_support_to_records_idx` (`records_support_id` ASC) VISIBLE,
  INDEX `fk_records_link_to_records_idx` (`records_link_id` ASC) VISIBLE,
  INDEX `fk_container_to_records_idx` (`container_id` ASC) INVISIBLE,
  INDEX `fk_classification_to_records_idx` (`classification_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbms`.`retention_sort`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`retention_sort` (
  `retention_sort_id` INT NOT NULL,
  `retention_sort_code` VARCHAR(10) NOT NULL,
  `retention_sort_title` VARCHAR(30) NOT NULL,
  `retention_sort_comment` VARCHAR(100) NULL,
  PRIMARY KEY (`retention_sort_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbms`.`retention`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`retention` (
  `retention_id` INT NOT NULL AUTO_INCREMENT,
  `retention_duration` INT NOT NULL,
  `retention_sort` INT NOT NULL,
  `retention_reference` TEXT NOT NULL,
  `retention_sort_id` INT NOT NULL,
  PRIMARY KEY (`retention_id`),
  INDEX `fk_retention_sort_to_retention_idx` (`retention_sort_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbms`.`organization_classification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`organization_classification` (
  `organization_id` INT NOT NULL,
  `classification_id` INT NOT NULL,
  PRIMARY KEY (`organization_id`, `classification_id`),
  INDEX `fk_classification_to_organization_classification_idx` (`classification_id` ASC) VISIBLE,
  INDEX `fk_organization_to_organization_classification_idx` (`organization_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbms`.`user_classification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`user_classification` (
  `user_id` INT NOT NULL,
  `classification_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `classification_id`),
  INDEX `fk_classification_to_user_idx` (`classification_id` ASC) VISIBLE,
  INDEX `fk_user_to_classification_idx` (`user_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbms`.`retention_classification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`retention_classification` (
  `retention_id` INT NOT NULL,
  `classification_id` INT NOT NULL,
  PRIMARY KEY (`retention_id`, `classification_id`),
  INDEX `fk_classification_to_retention_classification_idx` (`classification_id` ASC) VISIBLE,
  INDEX `fk_retention_to_retention_classification_idx` (`retention_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbms`.`dolly_records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`dolly_records` (
  `basket_id` INT NOT NULL,
  `records_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`basket_id`, `records_id`),
  INDEX `fk_records_to_dolly_records_idx` (`records_id` ASC) VISIBLE,
  INDEX `fk_basket_to_dolly_records_idx` (`basket_id` ASC) VISIBLE,
  INDEX `fk_user_to_dolly_records_idx` (`user_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbms`.`records_keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`records_keywords` (
  `records_id` INT NOT NULL,
  `keyword_id` INT NOT NULL,
  PRIMARY KEY (`records_id`, `keyword_id`),
  INDEX `fk_keywords_to_records_idx` (`keyword_id` ASC) VISIBLE,
  INDEX `fk_records_to_keywords_idx` (`records_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbms`.`loan_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`loan_type` (
  `loan_type_id` INT NOT NULL,
  `loan_type_title` VARCHAR(30) NOT NULL,
  `loan_type_observation` TEXT(250) NULL,
  PRIMARY KEY (`loan_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbms`.`docnum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`docnum` (
  `docnum_id` INT NOT NULL,
  `docnum_path` VARCHAR(100) NOT NULL,
  `docnum_sha` VARCHAR(250) NOT NULL,
  `docnum_date` DATETIME NOT NULL,
  `docnum_extension` VARCHAR(10) NOT NULL,
  `records_id` INT NOT NULL,
  PRIMARY KEY (`docnum_id`),
  INDEX `fk_records_to_docnum_idx` (`records_id` ASC) VISIBLE,
  CONSTRAINT `fk_docnum_records1`
    FOREIGN KEY (`records_id`)
    REFERENCES `dbms`.`records` (`id_records`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbms`.`loan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`loan` (
  `loan_id` INT NOT NULL,
  `loan_title` VARCHAR(100) NOT NULL,
  `user_id` INT NOT NULL,
  `records_id` INT NOT NULL,
  PRIMARY KEY (`loan_id`),
  INDEX `fk_loan_user2_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_loan_records2_idx` (`records_id` ASC) VISIBLE,
  CONSTRAINT `fk_loan_user2`
    FOREIGN KEY (`user_id`)
    REFERENCES `dbms`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loan_records2`
    FOREIGN KEY (`records_id`)
    REFERENCES `dbms`.`records` (`id_records`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbms`.`return`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbms`.`return` (
  `return_id` INT NOT NULL,
  `loan_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `return_date` DATE NOT NULL,
  `return_observation` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`return_id`),
  INDEX `fk_loan_to_return_idx` (`loan_id` ASC) VISIBLE,
  INDEX `fk_user_to_return_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_return_loan1`
    FOREIGN KEY (`loan_id`)
    REFERENCES `dbms`.`loan` (`loan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_return_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `dbms`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
